### PR TITLE
 Category issue fixed for WP-4.9

### LINKED ISSUE #10: Please fix category undefined issue fixed for WP-4.9

### LINKED ISSUE #12: Update Version number readme.txt file

### PR DESCRIPTION
**Pull request by aniljadhavmca**
Fix #10 
Fix #12

### CODE REVIEW

File: includes/changelog-taxonomy-template.php [hunk 1]
```diff
@@ -21,7 +21,7 @@
 				<?php
 					$all_prodcut_url = site_url() . '/changelog';
 					echo '<h1 class="page-title">' . single_cat_title( '', false ) . '</h1>';
-					echo "<a href='$all_prodcut_url'>All Products</a> / " . single_cat_title( '', false );
+					echo "<a href='$all_prodcut_url'>All Changelogs</a> / " . single_cat_title( '', false );
```
Comment (Nikschavan) [inline includes/changelog-taxonomy-template.php]: Make the string translatable and also `$all_prodcut_url` should be escaped.

File: classes/class-bsf-changelog-post-type.php [hunk 2]
```diff
@@ -61,10 +61,10 @@ public static function register_taxonomies() {
 				'show_ui'               => true,
 				'query_var'             => true,
 				'show_admin_column'     => true,
+				'hierarchical'          => true,
 				'rewrite'          => array(
-					'slug'         => 'product',
+					'slug'         => apply_filters( 'changelog_taxonomy', 'product' ),
```
Comment (Nikschavan) [inline classes/class-bsf-changelog-post-type.php]: The filter name should be unique. Add a prefix
